# Generated by Django 6.1.1 on 2026-09-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('client_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('topic', models.CharField(max_length=300, verbose_name='Тема')),
                ('meeting_type', models.CharField(
                    choices=[('video', 'Видеозвонок'), ('audio', 'Аудиозвонок'), ('personal', 'Личная встреча')],
                    default='video', max_length=20, verbose_name='Тип встречи',
                )),
                ('recording_url', models.URLField(blank=True, verbose_name='Ссылка на запись')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['date', 'time'],
                'constraints': [models.UniqueConstraint(fields=('date', 'time'), name='unique_slot')],
            },
        ),
    ]
